### ISSUE TITLE
Copyright details are missing in the LICENSE

### ISSUE THREAD

**Issue by shahpiyushv** [jdlambert/micro_tz_db#5]
The [LICENSE](https://github.com/jdlambert/micro_tz_db/blob/master/LICENSE) does not have name and year. Can you add those?

**Comment by jdlambert** [comment]
Sorry, I seem to have missed the notification for this issue.

Okay, I've added mine. I'll wait for the parent repo to add a name & year, and then I'll properly reference them in the License as well.
